# Ex6 - Sistemas Lineares - Ismael Marinho

In [8]:
import numpy as np
import scipy.linalg as sla

## Algoritmo 1

In [1]:
sist_lin_diag = lambda A, b: b/A.diagonal()

## Algoritmo 1.2

In [72]:
def sist_lin_tri_sup(A,b):
    n = len(b)
    x = np.empty(n)
    x[-1] = b[-1]/A[-1, -1]
    for i in range(n-2, -1, -1):
        x[i] = (b[i] - np.sum(A[i, i+1:]*x[i+1:]))/A[i, i]
    return x

## Algoritmo 1.3

In [4]:
def sist_lin_tri_inf(A,b):
    n = len(b)
    x = np.empty(n)
    x[0] = b[0]/A[0, 0]
    for i in range(1,n):
        x[i] = (b[i] - np.sum(A[i,:i]*x[:i]))/A[i,i]
    return x

## Exercicio 1
### Classifique os sistemas abaixo com relação a quantidade e existência de soluções.
### a)
$x + 2y + 3z = 1$  
$4x + 5y + 6z = 1$  
$7x + 8y + 9z = 1$  

### b)

$2x + 3y = 10$  
$−4x − 6y = −10$

In [14]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
b = np.array([1, 1, 1])

True if np.linalg.matrix_rank(A) == np.linalg.matrix_rank(np.c_[A, b]) else False

True

In [15]:
C = np.array([[2, 3], [-4, -6]])
b = np.array([10, -10])

True if np.linalg.matrix_rank(C) == np.linalg.matrix_rank(np.c_[C, b]) else False

False

## Exercicio 1.2

$3x_1 + 4x_2 − 5x_3 + x_4 = −10$  
$x_2+ x_3 − 2x_4 = −1$  
$4x_3 − 5x_4 = 3$  
$2x_4 = 2$ 

In [86]:
A = np.array([[3, 4, -5, 1],[0, 1, 1, -2],[0, 0, 4, -5],[0, 0, 0, 2]])
b1 = np.array([-10, -1, 3, 2])

Primeiro devemos ver o tamanho do b que normalmente será o número de icógnitas(no sistema SPD) que iremos descobrir os valores.

In [87]:
n = len(b1)

Criamos o vector que irá conter os valores que iremos descobrir das icógnitas.

In [88]:
x = np.empty(n)

Iremos adicionar primariamente o valor do ultimo "x" / ultima icógnita, e com ela iremos ir substituindo gradativamente até encontrar todas os valores.

In [89]:
x[-1] = b1[-1]/A[-1, -1]

Para substituir gradualmente pegamos os coeficientes daquela posicao para frente "i + 1" e multiplicamos pelo array/matriz do "x" daquela posição em diante também, depois somamos usando o método sum. E por fim pegamos o valor do "b" naquela posicao e subtraímos pela soma e dividimos pelo coeficiente daquela posicao.

In [90]:
for i in range(n-2, -1, -1):
    x[i] = (b1[i] - np.sum(A[i,i+1:]*x[i+1:]))/A[i,i]

Resultado:

In [91]:
print(x)
print(A.dot(x))

[ 1. -1.  2.  1.]
[-10.  -1.   3.   2.]


## Exercicio 1.3

$3x_1 = 4$  
$2x_1 + x_2 = 2$  
$x_1 + x_3 = 4$  
$x_1 + x_2 + x_3 + x_4 = 2$  

In [92]:
C = np.array([[3, 0, 0, 0],[2, 1, 0, 0],[1, 0, 1, 0],[1, 1, 1, 1]])
b2 = np.array([4, 2, 4, 2])

Assim como no Exemplo 1.2, devemos pegar o numero de icógnitas

In [93]:
n = len(b2)

Criamos o vector que irá conter os valores que iremos descobrir das icógnitas.

In [94]:
x = np.empty(n)

Como a triangular é inferior iremos adicionar primariamente o valor do primeiro "x" / primeira icógnita.

In [95]:
x[0] = b2[0]/C[0, 0]

Para substituir gradualmente pegamos os coeficientes até aquela posicao e multiplicamos pelo array/matriz do "x" também até aquela posição, depois somamos usando o método sum. E por fim pegamos o valor do "b" naquela posicao e subtraímos pela soma e dividimos pelo coeficiente daquela posicao, assim como a triangular superior.

In [96]:
for i in range(1,n):
        x[i] = (b2[i] - np.sum(C[i,:i]*x[:i]))/C[i,i]

Resultado:

In [97]:
print(x)
print(C.dot(x))

[ 1.33333333 -0.66666667  2.66666667 -1.33333333]
[4. 2. 4. 2.]


## Exercicio 1.4

### Implemente uma função, cujos parâmetros de entrada sejam somente a matriz de coeficientes e o vetor de termos independentes e que calcule o vetor solução para qualquer um dos casos triviais vistos aqui. Atente para o fato de que a própria função terá de verificar se a matriz de coeficientes é diagonal, triangular superior ou inferior e não o usuário.

In [98]:
def linear_trivial(A, b):
    if (A == np.tril(A)).all():
        return sist_lin_tri_inf(A,b)
    elif (A == np.triu(A)).all():
        return sist_lin_tri_sup(A,b)
    else:
        return sist_lin_diag(A, b)

In [99]:
print(linear_trivial(A, b1))
print(linear_trivial(C, b2))

[ 1. -1.  2.  1.]
[ 1.33333333 -0.66666667  2.66666667 -1.33333333]
